name: Test and Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  packages: read
  actions: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and run tests with JaCoCo
        run: |
          mvn -N wrapper:wrapper
          ./mvnw clean verify
        continue-on-error: true

      - name: Upload JaCoCo HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-html-report
          path: target/site/jacoco/
          retention-days: 7

      - name: Check Coverage Threshold
        if: always()
        run: |
          echo "Checking JaCoCo coverage..."
          COVERAGE=$(awk -F',' '
            NR>1 { missed += $4; covered += $5; }
            END {
              total = missed + covered;
              if (total > 0) {
                percent = (covered / total) * 100;
                printf "%.0f", percent;
              } else {
                print 0;
              }
            }' target/site/jacoco/jacoco.csv)

          echo "Coverage: ${COVERAGE}%"

          if [ -z "$COVERAGE" ] || [ "$COVERAGE" -lt 70 ]; then
            echo "❌ Coverage below threshold (70%)"
            exit 1
          else
            echo "✅ Coverage is adequate (${COVERAGE}%)"
          fi
